# Generated by Django 4.1.4 on 2022-12-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='language',
        ),
        migrations.AlterField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.channeltype'),
        ),
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.ManyToManyField(to='media.language'),
        ),
    ]
