# Generated by Django 4.1.4 on 2022-12-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_channel_language_alter_channel_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='genre',
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.ManyToManyField(to='media.genre'),
        ),
    ]
