version: '3'
services:
  api:
    image: python:3.8-slim
    container_name: immfly-django-api
    expose:
      - "3000"
    volumes:
      - "./api:/usr/src/app"
    working_dir: /usr/src/app
    command: bash -c "/usr/src/app/entrypoint.sh"
  
  httpd:
    image: nginx:1.22
    container_name: immfly-prod
    ports:
      - "80:80"
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./api/static:/usr/share/nginx/html/static"
    depends_on:
      - api